### ISSUE TITLE
输入用户名密码点登陆会有错误

### ISSUE THREAD

**Issue by fuhehe** [kbengine/kbengine_cocos2d_js_demo#3]
![qq 20181226113412](https://user-images.githubusercontent.com/10858962/50430981-37aa4100-0902-11e9-8a2a-e7d0bc6a741e.png)

**Comment by jay602** [comment]
服务器用1.x版本的，登录没问题。你的服务器是哪个版本

**Comment by fuhehe** [comment]
不好意思，用的是2.x的。换成1.x的可以了 👍
